### ISSUE TITLE
Type of `show_controls` in the example code

### ISSUE THREAD

**Issue by himoto** [biomass-dev/biomass#151]
Hi @formersbach,
I thinks the type of `show_controls` in the example code of `dynamic_plot()` should be boolean, not string:
```python
model.dynamic_plot(save_dir='example_dir', file_name='nfkb_dynamic.html' show_controls='True', which_controls=['physics', 'layout'])
```

If yes, I have a fix-doc branch and fix this.
Thank you!

**Comment by formersbach** [comment]
True, good catch!
Should I make the changes to save_dir on fix-doc branch as well?
