### ISSUE TITLE
Using BioMASS without Graphviz

### ISSUE THREAD

**Issue by himoto** [biomass-dev/biomass#161]
### Discussed in https://github.com/biomass-dev/biomass/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **himoto** July 23, 2022</sup>
BioMass requires users to manually install [Graphviz](https://www.graphviz.org) for graph visualization but some packages derived from biomass, e.g., [pasmpy](https://github.com/pasmopy/pasmopy), do not need it. Currently if we run `import biomass` without Graphviz, it will raise an ImportError.
I would like to make this optional so that biomass-derived packages can be run without error even if Graphviz is not installed.

**Ideas:**
- [x] Move `pygraphviz` and `pyvis` from requirements.txt to extras_require in setup.py
- [x] Modify `graph.py` as follows:

```python

def to_graph(self):
    try:
        import pygraphviz as pgv
    except ImportError:
        print("pygraphviz is required to run this function.")
    ...

def dynamic_plot(self, ...):
    try:
        from pyvis.network import Network
    except ImportError:
        print("pyvis is required to run this function.")

```

@formersbach
I would be grateful if you could give me comments on this. I have a [branch working on this](https://github.com/himoto/biomass/tree/wo-graphviz) and if it's ok, I will send a PR.</div>

**Comment by formersbach** [comment]
I agree with the changes!
Have you checked whether import pygraphviz raises an ImportError when graphviz is not installed? I suspect it might be able to import pygraphviz, but fail further down the line.

**Comment by himoto** [comment]
Hi @formersbach, thanks for your reply. I am sorry but I was wrong. When you run `import biomass` without Graphviz, it will not raise ImportError but show different error message. Please refer to https://github.com/pasmopy/pasmopy/actions/runs/2742861321.

**Comment by formersbach** [comment]
Hey @himoto, So it already fails during the installation... 
I found this code which allows to install a package inside a script:
```python
import subprocess
import sys
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
```
We could replace
```python
try:
    import pygraphviz as pgv 
```
with
```python
try:
    install("pygraphviz") #install being the function defined above
    import pygraphviz
```
Note that `subprocess.check_call` will raise a CalledProcessError if installation fails.

**Comment by himoto** [comment]
@formersbach 
Sorry for confusing you but the error message above is raised **before** updating the code.
It works as I expected after the update.

**Comment by formersbach** [comment]
Aah I see, I did notice the attached pull request. Changes look good!

P.S.: Why are you working at 3 in the mornign? 😄
