### ISSUE TITLE
Phosphorylation generates duplicate ODE

### ISSUE THREAD

**Issue by formersbach** [biomass-dev/biomass#183]
### Description:

If "is phosphorylated" reaction rule is used with a unphosphorylated species that has been previously used, a second ODE is mistakenly generated. 
### Reproduce:

Text file containing:
```
TNFR phosphorylates Ikk --> pIkk   
Ikk is phosphorylated <--> pIkk
pIkk is phosphorylated <--> ppIkk
```
Convert to model:
```python
from biomass import Text2Model, create_model
model = Text2Model("test.txt")
model.convert(overwrite=True)
model = create_model(test)
```
### Proposed changes:

Add missing format string in line 1099:
```python
elif "dydt[V.{phosphorylated_form}]" in eq:
```
to
```python
elif f"dydt[V.{phosphorylated_form}]" in eq:
```

**Comment by himoto** [comment]
Hi @formersbach, thanks for your report.
I created a pull request #184  to resolve this issue.
