### ISSUE TITLE
Unable to run provided models

### ISSUE THREAD

**Issue by lhdp0110** [biomass-dev/biomass#194]
I am a beginner in both Python and data modeling and am having difficulties figuring out how to run this module based on the tutorials alone. I have been attempting to run the models provided but cannot get it to work. 
I had some help to install the module using pip, then I have downloaded the biomass_master file, and created a Python text file called biomass_test.py within the Nakakuki_Cell_2010 folder using Visual Studio Code. I have copied/pasted the commands
`` 
from biomass import create_model
from biomass.models import Nakakuki_Cell_2010

model = create_model(Nakakuki_Cell_2010.__package__, show_info=True)
`` 

within that text file, and ran it in a Python terminal in VS Code. It gives me the following error:
` `FileNotFoundError: [Errno 2] No such file or directory: 'biomass\\models\\Nakakuki_Cell_2010\\ode.py'`` 
The biomass_test.py and ode.py files are both in the Nakakuki_Cell_2010 folder. Could you please advise on what I may be doing wrong?

**Comment by himoto** [comment]
Hi @lhdp0110, thank you for your inquiry.

Could you tell me which biomass version you are using?
You can check your current biomass version via:
```python
import biomass
biomass.__version__
```
If it is less than 0.7, can you please use the latest one?

**Comment by himoto** [comment]
Thanks your your detailed explanation.

If you still get error even when run the following code in a new working directory, please do let me know here.

```
git clone https://github.com/biomass-dev/biomass
cd biomass
```
Then open python or jupyter:
```python
from biomass import create_model
from biomass.models import Nakakuki_Cell_2010

model = create_model(Nakakuki_Cell_2010.__package__, show_info=True)
```

**Comment by lhdp0110** [comment]
Yes, I am still getting the same error after those steps

**Comment by himoto** [comment]
If you run the following code in your working directory, you get `True`, yes?

```python
import os
os.path.isfile("biomass/models/Nakakuki_Cell_2010/ode.py")
```

**Comment by lhdp0110** [comment]
Actually it returns false

**Comment by himoto** [comment]
I guess you are working in a wrong directory.
After you run the following code:

```
git clone https://github.com/biomass-dev/biomass
cd biomass
```

This must return `True` (in other words you will need to work in a directory where this returns true).
```python
import os
os.path.isfile("biomass/models/Nakakuki_Cell_2010/ode.py")
```
As you can see the [`ode.py`](https://github.com/biomass-dev/biomass/blob/master/biomass/models/Nakakuki_Cell_2010/ode.py) file does exist in Nakakuki_Cell_2010 folder.

In your working directory, can you see files, e.g., `requirements.txt`?

**Comment by lhdp0110** [comment]
I have just switched over to Mac and finally got it to say True. Would you please explain what the line "from biomass import create_model" performs? When I run it from within the biomass root folder as my working directory, it says:
ImportError: cannot import name 'create_model' from 'biomass' (unknown location)
Should there be a file called create_model or is this a class within one of the files?

Thank you again for your much-appreciated help

**Comment by himoto** [comment]
If you install biomass via `pip install biomass`, it should work no matter whichever directory you are in.
Assuming that your biomass is installed via `git clone`.
> Would you please explain what the line "from biomass import create_model" performs?

When you run `from biomass import create_model`,  Python first tries to read [`__init__.py` file in biomass/](https://github.com/biomass-dev/biomass/blob/master/biomass/__init__.py).
In that file, I have `from .core import *`.
In the `core.py` file, I have `__all__ = ["Model", "create_model", "optimize", "run_simulation", "run_analysis"]`.
This is why we can call `create_model` function from `biomass`. I believe this does not depend on which OS you use.

If you still have any questions, feel free to ask :)
