### ISSUE TITLE
Typo in state_transition rule

### ISSUE THREAD

**Issue by formersbach** [biomass-dev/biomass#220]
### Description:

Modifier parsed with state_transition reaction rule leads to wrong kinetic information.

### Reproduce:
Text file containing:

`A + B --> A + pB`

Convert to model:
```python
from biomass import Text2Model, create_model
model = Text2Model("test.txt")
model.convert(overwrite=True)
print(model.kinetics.rate)
```
### Expected:
kf1 * pB * A

### Observed:

kf1 * pB * A]

### Proposed fix:

remove typo in line 1724 of reaction_rules.py:
`[f"{modifier}]"` to `[f"{modifier}"`

**Comment by formersbach** [comment]
Hey @himoto ! Hope you made it home safely :)
If there's no objection I'll open a pull request and implement the fix.

**Comment by himoto** [comment]
Hi @formersbach, thanks for your report.
Can you please fix this?
