### ISSUE TITLE
Adding docker image to readme

### ISSUE THREAD

**Issue by johannesnicolaus** [biomass-dev/biomass#62]
I have made a docker image for the newest version:
https://hub.docker.com/repository/docker/jnicolaus/biomass

Haven't tested all the functions but so far seemed to work fine using singularity on HPC. 

I can make a pull request if it will be required for the readme.

**Comment by himoto** [comment]
Hi @johannesnicolaus
Thank you for your great work! Can you please send a pull request to [`container`](https://github.com/okadalabipr/biomass/tree/container) branch in https://github.com/okadalabipr/biomass?
