### ISSUE TITLE
Error for the simulation example in the readme

### ISSUE THREAD

**Issue by johannesnicolaus** [biomass-dev/biomass#63]
The following error was produced when running the example in the readme

```python
RuntimeWarning: invalid value encountered in double_scalars
  + (y[V.Fn] / x[C.KF31]) ** x[C.nF31]
```

The code:

```python
from biomass import Model, optimize
from biomass.models import Nakakuki_Cell_2010

model = Model(Nakakuki_Cell_2010.__package__).create()
run_simulation(model, viz_type="average", stdev=True)
```

I think it is caused by an undefined parameter and thus, I propose changing the model used in the exampleto another model that does not require manual input of parameters, or to pre-input the default parameter for the model. 

Please let me know if this is a misunderstanding.

**Comment by himoto** [comment]
Hi @johannesnicolaus,

Did you perform parameter estimation using `optimize()` function before running `run_simulation(model, viz_type="average", stdev=True)`?
You need optimized parameter sets to visualize simulation results like [this](https://github.com/biomass-dev/biomass/tree/master/tests/out).

You can get them by running:

```python
from biomass import Model, optimize
from biomass.models import Nakakuki_Cell_2010

model = Model(Nakakuki_Cell_2010.__package__).create()

optimize(model, x_id=range(1, 11))  # getting 10 parameter sets
```

then, visualize results through:

```python
from biomass import run_simulation

run_simulation(model, viz_type="average", stdev=True)
```

Cheers,

Hiroaki

**Comment by johannesnicolaus** [comment]
I see, so basically just a misunderstanding. Thanks!

**Comment by himoto** [comment]
Anytime!
